--return {
--  {
--    "folke/tokyonight.nvim",
--    opts = {
--      transparent = true,
--      styles = {
--        sidebars = "transparent",
--        floats = "transparent",
--      },
--    },
--  },
--}
return { "catppuccin/nvim", name = "catppuccin", priority = 1000 }
